// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf1snoo-tjLMTWvHGPISC5mhwnIluJxb8',
    appId: '1:596775451407:web:c9649caee8c7d16b73dc7a',
    messagingSenderId: '596775451407',
    projectId: 'gooddeedssalon',
    authDomain: 'gooddeedssalon.firebaseapp.com',
    storageBucket: 'gooddeedssalon.appspot.com',
    measurementId: 'G-QB6Q2KFCRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sQ_EKp92av1wuGQBuaXhXNCdULmFuhc',
    appId: '1:596775451407:android:c66ac43ba73f16c273dc7a',
    messagingSenderId: '596775451407',
    projectId: 'gooddeedssalon',
    storageBucket: 'gooddeedssalon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR62N6B2eKB81cApA_pWKphxj_4TuI3n8',
    appId: '1:596775451407:ios:46f0701bfeaf0ab873dc7a',
    messagingSenderId: '596775451407',
    projectId: 'gooddeedssalon',
    storageBucket: 'gooddeedssalon.appspot.com',
    iosClientId: '596775451407-dg3mpsr1d9r71ncb5emal3rhisd6imit.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodDeedsSalon',
  );
}
